apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: murakan001/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: CUSTOMER_SERVICE_URL
              value: "http://customer-service:8003"
            - name: MENU_SERVICE_URL
              value: "http://menu-service:8002"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP